version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: organization_info
